# Generated by Django 5.1.7 on 2025-03-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='bg_changed',
            field=models.ImageField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
